### ISSUE TITLE
Inverted-Mode for Chinch

### ISSUE THREAD

**Issue by pascaltippelt** [guyc/RC5#1]
Some old Philips Hifi-Systems have an RC5 Chinch port. This uses, as far as I understand it, the same protocoll but inverted. Could you please add an inverted mode? You will also have to change the pin config from "INPUT_PULLUP" to "INPUT", as the Chinch works as Input and Output an a pulled up signal would overwrite everything.

**Comment by guyc** [comment]
To simply invert the signal you could make a tiny change here:
https://github.com/guyc/RC5/blob/master/RC5.cpp#L137

```
this->decodePulse(value, elapsed);
```

to 

```
this->decodePulse(!value, elapsed);
```

However you'll note from the comments that the input value read from the IR receiver is already inverted, and compensated for, so you may not need to invert the signal at all.  Do you have any documentation for the Chinch port?

**Comment by pascaltippelt** [comment]
The only "documentation" I have is the information that the RC5-Chinch port is the inverted signal of what you get from an infrared reciver and works at 5V logic. 

I testet your library and the first thing I noticed was, that the input must not be used as PULLUP, as it blocks the RC5 port, because it is used in both directions. I'll try your code this evening.

Thank you!

**Comment by pascaltippelt** [comment]
Okay, that's the way it works! Just (re)invert the signal as @guyc described and use
pinMode(pin, INPUT);
and it works perfectly out of the box!
