### ISSUE TITLE
Implementing your code as is fails

### ISSUE THREAD

**Issue by jegjessing** [guyc/RC5#2]
Compilser says that address, command and toggle was not declared in this scope

**Comment by clearwater** [comment]
Please provide the complete error message from the compiler.

**Comment by Kryolisc** [comment]
Have you declared those three variables correctly?
You have to paste the following code right before the `if (rc5.read(&toggle, &address, &command))` part:

```
  unsigned char toggle;
  unsigned char address;
  unsigned char command;
```

This should solve the problem.

Just look at the example code provided in [RC5/examples/RC5Decode/RC5Decode.ino](https://github.com/guyc/RC5/blob/master/examples/RC5Decode/RC5Decode.ino)
